### ISSUE TITLE
checkCudaErrors is undefined...

### ISSUE THREAD

**Issue by antithing** [yunchih/ORB-SLAM2-GPU2016-final#3]
Hi! thank you for making this code available! I am trying to build on windows, CUDA 8, and am getting errors...

in `Cuda.cu`:
`checkCudaErrors is undefined`
`cudaDeviceSynchronize is undefined`

and the same error in `Allocator_gpu.cu`
`checkCudaErrors(cudaMallocManaged(&mat->data, mat->step * rows)); //checkCudaErrors is undefined.`

and in `Orb_gpu.cu`:

`blockIdx is undefined`
`threadIdx is undefined`.

Will this code build on windows? If you have any idea what I am missing, it would be much appreciated! Thanks again.

**Comment by yunchih** [comment]
I never have the chance to build on Windows.  

Are you able to build other Cuda sample code?  
`blockIdx` and `threadIdx` are essential built-in variables in Cuda kernel; if Visual Studio said it could not find it, I bet you probably had a broken Cuda setup.

**Comment by antithing** [comment]
thanks for getting back to me. I just needed to add CUDA properties to my visual studio project. Now I have a new issue, i cannot find:
`helper_cuda.h`

which is an include. Where is this file located? is it part of CUDA? 

thanks again!

**Comment by yunchih** [comment]
`checkCudaErrors` is defined in `helper_cuda.h`, which is included in Cuda's samples directory.
You might want to add that directory to your VS project include path.  Something like `$CUDA_HOME\samples\common\inc\` as documented [here](http://stackoverflow.com/questions/19352941/trying-to-get-cuda-working-sample-cant-find-helper-cuda-h)

**Comment by antithing** [comment]
Hi again, I have the lib building now, but am seeing one last error when i try to compile a sample project that calls it.  (i am using the `stereo_kitti` example that comes with orbslam2, should this work with your updates? ) The error I see is:

`unresolved external symbol "public: static class cv::cuda::Stream __cdecl cv::cuda::StreamAccessor::wrapStream(struct CUstream_st *)" (?wrapStream@StreamAccessor@cuda@cv@@SA?AVStream@23@PEAUCUstream_st@@@Z)	(Fast_gpu.cu.obj)	1	`

I have linked to the opencv lib that holds `cv::cuda::StreamAccessor::wrapStream`, (opencv_cudaarithm320.lib), so I am a bit stuck! Any help you could give me would be much appreciated. Thank you again.

**Comment by antithing** [comment]
Rebuilding openCv from scratch, and linking the new libs has solved this. I think I had libs from different builds linked.
