### ISSUE TITLE
cannot find -lnvToolsExt

### ISSUE THREAD

**Issue by Sangheli** [yunchih/ORB-SLAM2-GPU2016-final#6]
when I try to build source code, I've got error.

GPU - 1050ti 4gb
Cuda toolkit 8
Cudnn 6

[ 29%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/ORBmatcher.cc.o
[ 32%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/FrameDrawer.cc.o
[ 35%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Converter.cc.o
[ 38%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/MapPoint.cc.o
[ 41%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/KeyFrame.cc.o
[ 44%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Map.cc.o
[ 47%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/MapDrawer.cc.o
[ 50%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Optimizer.cc.o
[ 52%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/PnPsolver.cc.o
[ 55%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Frame.cc.o
[ 58%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/KeyFrameDatabase.cc.o
[ 61%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Sim3Solver.cc.o
[ 64%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Initializer.cc.o
[ 67%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Viewer.cc.o
[ 70%] Linking CXX shared library lib/libORB_SLAM2.so
**/usr/bin/ld: cannot find -lnvToolsExt**
collect2: error: ld returned 1 exit status
CMakeFiles/ORB_SLAM2.dir/build.make:666: recipe for target 'lib/libORB_SLAM2.so' failed
make[2]: *** [lib/libORB_SLAM2.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ORB_SLAM2.dir/all' failed
make[1]: *** [CMakeFiles/ORB_SLAM2.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Sangheli** [comment]
solved by:

sudo ln -s /usr/local/cuda-8.0/lib64/libnvToolsExt.so /usr/lib64/libnvToolsExt.so

**Comment by anakin0620** [comment]
For those who have this issue on your NVIDIA Jetson TX2/Xavier. Install OpenCV by yourself will fix it.  Purge the OpenCV comes with JetPack and install it by your self.
